version: '3.8'

services:
  app:
    build: .
    image: vidzap:dev
    container_name: vidzap:dev
    volumes:
      - ..:/vidzap:cached
      - /home/syaofox/.agents:/home/vscode/.agents
    command: sleep infinity
